# Generated by Django 4.2.7 on 2025-08-08 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('company_number', models.CharField(max_length=20, unique=True)),
                ('company_status', models.CharField(blank=True, max_length=50)),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('dissolved_date', models.DateField(blank=True, null=True)),
                ('registered_office_address', models.JSONField(default=dict)),
                ('nature_of_business', models.TextField(blank=True)),
                ('sic_codes', models.JSONField(default=list)),
                ('accounts_next_due_date', models.DateField(blank=True, null=True)),
                ('confirmation_statement_next_due_date', models.DateField(blank=True, null=True)),
                ('companies_house_url', models.URLField(blank=True, max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=1)),
                ('requires_proxy', models.BooleanField(default=False)),
                ('success_rate', models.FloatField(default=0.0)),
                ('headers', models.JSONField(default=dict)),
                ('cookies', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('timeout', 'Timeout'), ('not_found', 'Not Found')], max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('data_found', models.JSONField(default=dict)),
                ('error_details', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('scraping_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scraper.scrapingjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapingsource')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON'), ('airtable', 'Airtable')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('include_directors', models.BooleanField(default=True)),
                ('include_contacts', models.BooleanField(default=True)),
                ('verified_contacts_only', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('download_url', models.URLField(blank=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scraping_jobs', models.ManyToManyField(related_name='export_requests', to='scraper.scrapingjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director_type', models.CharField(choices=[('person', 'Natural Person'), ('corporate', 'Corporate Entity')], default='person', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.JSONField(default=dict)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('address', models.JSONField(default=dict)),
                ('appointed_on', models.DateField(blank=True, null=True)),
                ('resigned_on', models.DateField(blank=True, null=True)),
                ('officer_role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='scraper.company')),
            ],
            options={
                'ordering': ['-appointed_on'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='scraping_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='scraper.scrapingjob'),
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=50)),
                ('contact_value', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('companies_house', 'Companies House'), ('website', 'Company Website'), ('linkedin', 'LinkedIn'), ('google', 'Google Search'), ('manual', 'Manual Entry'), ('other', 'Other')], max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('verified', models.BooleanField(default=False)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='scraper.company')),
            ],
            options={
                'ordering': ['-confidence_score', '-found_at'],
                'unique_together': {('company', 'contact_type', 'contact_value')},
            },
        ),
    ]
