# Generated by Django 4.2.7 on 2025-08-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='scraper.director'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='relationship',
            field=models.CharField(choices=[('company', 'Company Contact'), ('director', 'Director Contact'), ('general', 'General Contact')], default='company', max_length=20),
        ),
    ]
